### PR TITLE
Ensure windows paths get escaped

### LINKED ISSUE #28: File paths not resolving properly on Windows
Using Windows 7, node 64bit v.6.11.1

It's not receiving file paths correctly.

Gets error message in terminal when running npm start:
 
```
Project is running at http://localhost:9000/
webpack output is served from /
Content not from webpack is served from C:\Users\giggs\Documents\robpack\demo\dist
webpack: wait until bundle finished: /
Hash: 53cdf8733c669c76be58
Version: webpack 3.3.0
Time: 4749ms
                                                          Asset     Size  Chunks
          Chunk Names
                                                      bundle.js   355 kB       0  [emitted
]  [big]  main
                                                     index.html     2 kB          [emitted
]
bower_components/webcomponentsjs/custom-elements-es5-adapter.js  1.62 kB          [emitted
]
        bower_components/webcomponentsjs/webcomponents-hi-ce.js  23.6 kB          [emitted
]
                   bower_components/webcomponentsjs/gulpfile.js  5.09 kB          [emitted
]
     bower_components/webcomponentsjs/webcomponents-hi-sd-ce.js  72.6 kB          [emitted
]
           bower_components/webcomponentsjs/webcomponents-hi.js  9.72 kB          [emitted
]
       bower_components/webcomponentsjs/webcomponents-loader.js  3.15 kB          [emitted
]
         bower_components/webcomponentsjs/webcomponents-lite.js  83.5 kB          [emitted
]
        bower_components/webcomponentsjs/webcomponents-sd-ce.js  64.3 kB          [emitted
]
  [39] multi (webpack)-dev-server/client?http://localhost:9000 ./src/index.js 40 bytes {0}
 [built]
  [40] (webpack)-dev-server/client?http://localhost:9000 5.59 kB {0} [built]
  [41] ./node_modules/url/url.js 23.3 kB {0} [built]
  [43] ./node_modules/url/util.js 314 bytes {0} [built]
  [47] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [48] ./node_modules/ansi-regex/index.js 135 bytes {0} [built]
  [49] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
  [50] ./node_modules/sockjs-client/lib/entry.js 244 bytes {0} [built]
  [81] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
  [86] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [87] ./node_modules/events/events.js 8.33 kB {0} [built]
  [88] ./src/index.js 44 bytes {0} [built]
  [89] ./src/my-element.html 2.78 kB {0} [built]
  [90] ./node_modules/date-fns/format/index.js 10.1 kB {0} [built]
 [103] ./node_modules/polymer-webpack-loader/register-html-template.js 1.92 kB {0} [built]

    + 89 hidden modules

ERROR in ./src/my-element.html
obpackdemower_componentspolymerpolymer-element.html' in 'C:\Users\giggs\Documents\robpack\
demo\src'
 @ ./src/my-element.html 5:0-88
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:9000 ./src/index.js
Child html-webpack-plugin for "index.html":
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.ejs 2.49 kB {0} [b
uilt]
       [1] ./node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Failed to compile.
```
and in the console  

```
Uncaught Error: Cannot find module "C:UsersgiggsDocuments
obpackdemoower_componentspolymerpolymer-element.html"
    at webpackMissingModule (bundle.js:9646)
    at Object.<anonymous> (bundle.js:9646)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:9635)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:4097)
    at __webpack_require__ (bundle.js:20)
    at module.exports.ctor.super_ (bundle.js:63)
    at bundle.js:66
```

### PR DESCRIPTION
**Pull request by bryandcoulter**
Fixes #28 

Adds path.replace with a regular expression to ensure that paths get correctly escaped.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ import sourceMap from 'source-map';
 const domPred = predicates.AND(predicates.hasTagName('dom-module'));
 const linkPred = predicates.AND(predicates.hasTagName('link'));
 const scriptsPred = predicates.AND(predicates.hasTagName('script'));
+const windowsPathRegExp = new RegExp('\\\\', 'g');
```
Comment (ChadKillingsworth) [inline src/index.js]: I tend to prefer avoiding the `RegExp` constructor in most cases. `/\\\\/g` is equivalent here.

File: src/index.js [hunk 2]
```diff
@@ -60,7 +61,7 @@ class ProcessHtml {
         const ignoredFromPartial = ignoreLinksFromPartialMatches.filter(partial => href.indexOf(partial) >= 0);
 
         if (ignoreLinks.indexOf(href) < 0 && ignoredFromPartial.length === 0) {
-          source += `\nimport '${path}';\n`;
+          source += `\nimport '${path.replace(windowsPathRegExp, '\\\\')}';\n`;
```
Comment (ChadKillingsworth) [inline src/index.js]: This looks like you are replacing 2 backslashes with 2 backslashes. Am I missing something?

Comment (bryandcoulter) [inline src/index.js]: RegExp('\\', 'g'); returns as an invalid regular expression. I removed the constructor but it require RegExp('\\\\', 'g'); to work.

File: src/index.js [hunk 3]
```diff
@@ -60,7 +60,7 @@ class ProcessHtml {
         const ignoredFromPartial = ignoreLinksFromPartialMatches.filter(partial => href.indexOf(partial) >= 0);
 
         if (ignoreLinks.indexOf(href) < 0 && ignoredFromPartial.length === 0) {
-          source += `\nimport '${path}';\n`;
+          source += `\nimport '${path.replace(/\\/g, '\\\\')}';\n`;
```
Comment (michael-ciniawsky) [inline src/index.js]:
```
import { sep } from 'path'
...
const normalize = (str) => str.split(path.sep).join('/')
```
If I not mistaken webpack picks up unix paths with '/' accross all systems, but not :100:, otherwise `JSON.stringify(source)` ?

Comment (ChadKillingsworth) [inline src/index.js]: I'm getting ready to test this out on my windows box.

Comment (michael-ciniawsky) [inline src/index.js]: https://github.com/webpack-contrib/istanbul-instrumenter-loader/blob/master/test/utils/loader.js#L8

https://github.com/webpack/memory-fs/blob/master/lib/normalize.js

But not sure if it is the correct context in the code here :)

Comment (ChadKillingsworth) [inline src/index.js]: The regex replace works great on my windows box. The `JSON.stringify` doesn't - didn't try to dig into why (though it's a cool trick).

Comment (michael-ciniawsky) [inline src/index.js]: hmm... 🤔 kk I see normally this is what most loaders use to escape their contents, but seems to not apply here :)
